postgres_defaults: &postgres_defaults
  adapter:  postgresql
  encoding: UTF-8
  pool:     5

development_db_defaults: &development_db_defaults
  <<: *postgres_defaults
  username: postgres
  password: password
  host:     localhost
  port:     5432

cir_defaults: &cir_defaults
  adapter:  postgresql
  username: viewer
  password: viewer

cir_dev_default: &cir_dev_default
  host:     cirdev
  database: cir
  port:     5632

cir_dev_repositories: &cir_dev_repositories
  cirdev:
    <<: *cir_defaults
    <<: *cir_dev_default

cir_production_defaults: &cir_production_defaults
  <<: *postgres_defaults
  database: cir
  port:     5412

cirs_production: &cirs_production
  athena:
    <<: *cir_production_defaults
    host: athena.wicourts.gov
  artemis:
    <<: *cir_production_defaults
    host: artemis.wicourts.gov
  saber:
    <<: *cir_production_defaults
    host: saber.wicourts.gov
  plato:
    <<: *cir_production_defaults
    host: plato.wicourts.gov

# here's the meat of this file
development:
  <<: *development_db_defaults
  database: multidoc
  repositories:
    <<: *cir_dev_repositories

# here's the meat of this file
tr:
  <<: *development_db_defaults
  database: multidoc-tr
  repositories:
    <<: *cir_dev_repositories

test:
  adapter:  sqlite3
  database: db/test.sqlite3
  pool:     5
  timeout:  5000
  repositories:
    <<: *cir_dev_repositories
